Delete server command
deliciousbrains/spinupwp-cli pull request #18
Opened 2021-12-08 18:47 UTC by danielmlozano

Resolves #11 

Includes the `--force` and `--delete-on-provider` flags.

2021-12-09 09:18 UTC, A5hleyRich requested changes
@danielmlozano does this work against a local Spinup install for you? I get the following error:

> Undefined index: event_id

2021-12-09 09:18 UTC, A5hleyRich commented on app/Commands/Servers/DeleteCommand.php
> +        $delete = $this->option('force') || $this->confirm('Are you sure you want to delete this server?');
Before asking them to confirm, let's show an alert:

> You're about to delete "SERVER NAME"

Then update the confirm wording to:

> Do you wish to continue?

2021-12-09 09:18 UTC, A5hleyRich commented on app/Commands/Servers/DeleteCommand.php
> +    protected $signature = 'servers:delete {id?} {--force} {--profile=} {--delete-on-provider}';
Let's tidy this up and provide descriptions:

```
{server_id? : The server to delete}
{--d|delete-on-provider : Delete the server from the server provider (DigitalOcean, etc.)}
{--f|force : Delete the server without prompting for confirmation}
{--profile=}
```

2021-12-14 00:53 UTC, danielmlozano commented
Took me a while finding my own error. Since I cannot hit the API URL using Valet SSL (it throws a `curl` error), I added the "`verify => false`" option in the custom client, and that was causing the `event_id` error.

2021-12-16 11:30 UTC, A5hleyRich requested changes

2021-12-16 11:30 UTC, A5hleyRich commented on app/Commands/Servers/DeleteCommand.php
> +            $this->warn("You're about to delete \"{$server->name}\"");
This should be an `alert`.

2021-12-16 18:38 UTC, danielmlozano commented on app/Commands/BaseCommand.php
> +            if (!$this->spinupwp->hasApiKey() || !empty($this->config->get('api_url', $this->profile()))) {
My bad, it was part of my debugging for the `event_id` issue.

2021-12-17 10:17 UTC, A5hleyRich commented
💯

2021-12-17 10:17 UTC, merged