Get server command
deliciousbrains/spinupwp-cli pull request #9
Opened 2021-11-18 23:30 UTC by danielmlozano

`spinupwp servers:get <server_id>`

2021-11-22 13:55 UTC, A5hleyRich requested changes

2021-11-22 13:55 UTC, A5hleyRich commented on app/Commands/Servers/GetCommand.php
> +        ];
This needs to output everything returned from the API.

2021-11-22 13:55 UTC, A5hleyRich commented on app/Commands/Servers/GetCommand.php
> +            'Provider name' => $server->provider_name,
Provider **N**ame

2021-11-22 13:55 UTC, A5hleyRich commented on app/Commands/Servers/GetCommand.php
> +            'SSH port'      => $server->ssh_port,
SSH **P**ort

2021-11-22 15:30 UTC, A5hleyRich commented
@danielmlozano as discussed in Slack, can we also change the output to match the list commands? The table should have a border and the left column keys should be green.

2021-11-22 17:40 UTC, danielmlozano commented
@A5hleyRich Done. The only thing that I'm not sure about is that the SSH and Git keys are too large for the table.

2021-11-22 21:59 UTC, danielmlozano commented
@A5hleyRich added the `setColumnMaxWidth` method.

2021-11-23 08:57 UTC, A5hleyRich commented
💯

2021-11-23 08:57 UTC, merged